### ISSUE TITLE
Rake fails

### ISSUE THREAD

**Issue by nathenharvey** [chef-cft/habitat_workstation#11]
A new dependency has been added, `deep_merge`.

Without that gem, you get the following error when trying to run any rake tasks:

```rake aborted!
LoadError: cannot load such file -- deep_merge
/Users/nathenharvey/projects/chef-cft/habitat_workstation/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

We should either add a Gemfile or document this pre-requisite in the README.

**Comment by cheeseplus** [comment]
Nuked deep_merge cause it wasn't useful and hard to reason about ;)
