### ISSUE TITLE
Build 'amazon-ebs' errored: Error executing Chef: Non-zero exit status: 2300218

### ISSUE THREAD

**Issue by ubergeekgirl** [chef-cft/habitat_workstation#26]
amazon-ebs: * apt_package[git, tree, vim, emacs, nano] action install
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error executing Chef: Non-zero exit status: 2300218

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error executing Chef: Non-zero exit status: 2300218

==> Builds finished but no artifacts were created.
➜  habitat_workstation git:(patch1) ✗ rake "ami:build[ubuntu-1604,0.14.0]"
tee: logs/ubuntu-1604-hab-0.14.0.log: No such file or directory

**Comment by nathenharvey** [comment]
what command were you running here?
